### ISSUE TITLE
node js error npm start 

### ISSUE THREAD

**Issue by hishamkaram** [GeoNode/geonode-client#80]
cmd:
```
> geonode-viewer@0.0.3 start C:\Users\CartoLogic\Downloads\geonode-client-master
> mkdir -p dist && node_modules/.bin/webpack-dev-server --progress --colors --hot --inline

A subdirectory or file -p already exists.
Error occurred while processing: -p.
A subdirectory or file dist already exists.
Error occurred while processing: dist.

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! geonode-viewer@0.0.3 start: `mkdir -p dist && node_modules/.bin/webpack-dev-server --progress --colors --hot --inline`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the geonode-viewer@0.0.3 start script 'mkdir -p dist && node_modules/.bin/webpack-dev-server --progress --colors --hot --inline'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the geonode-viewer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     mkdir -p dist && node_modules/.bin/webpack-dev-server --progress --colors --hot --inline
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs geonode-viewer
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls geonode-viewer
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\CartoLogic\Downloads\geonode-client-master\npm-debug.log
```
log:
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.10.8
3 info using node@v6.9.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle geonode-viewer@0.0.3~prestart: geonode-viewer@0.0.3
6 silly lifecycle geonode-viewer@0.0.3~prestart: no script for prestart, continuing
7 info lifecycle geonode-viewer@0.0.3~start: geonode-viewer@0.0.3
8 verbose lifecycle geonode-viewer@0.0.3~start: unsafe-perm in lifecycle true
9 verbose lifecycle geonode-viewer@0.0.3~start: PATH: C:\Program Files (x86)\nvm\v6.9.1\node_modules\npm\bin\node-gyp-bin;C:\Users\CartoLogic\Downloads\geonode-client-master\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\Python27\;C:\Python27\Scripts;C:\Program Files (x86)\Lenovo\FusionEngine;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Common Files\lenovo\easyplussdk\bin;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\Git\cmd;C:\Program Files\Java\jdk1.8.0_111\bin;C:\Program Files (x86)\GDAL;%NVM_HOME%;%NVM_SYMLINK%;C:\Users\CartoLogic\AppData\Roaming\npm;C:\Users\CartoLogic\AppData\Local\Microsoft\WindowsApps;C:\Program Files (x86)\nvm;C:\Program Files\nodejs
10 verbose lifecycle geonode-viewer@0.0.3~start: CWD: C:\Users\CartoLogic\Downloads\geonode-client-master
11 silly lifecycle geonode-viewer@0.0.3~start: Args: [ '/d /s /c',
11 silly lifecycle   'mkdir -p dist && node_modules/.bin/webpack-dev-server --progress --colors --hot --inline' ]
12 silly lifecycle geonode-viewer@0.0.3~start: Returned: code: 1  signal: null
13 info lifecycle geonode-viewer@0.0.3~start: Failed to exec start script
14 verbose stack Error: geonode-viewer@0.0.3 start: `mkdir -p dist && node_modules/.bin/webpack-dev-server --progress --colors --hot --inline`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files (x86)\nvm\v6.9.1\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files (x86)\nvm\v6.9.1\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid geonode-viewer@0.0.3
16 verbose cwd C:\Users\CartoLogic\Downloads\geonode-client-master
17 error Windows_NT 10.0.14393
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v6.9.1
20 error npm  v3.10.8
21 error code ELIFECYCLE
22 error geonode-viewer@0.0.3 start: `mkdir -p dist && node_modules/.bin/webpack-dev-server --progress --colors --hot --inline`
22 error Exit status 1
23 error Failed at the geonode-viewer@0.0.3 start script 'mkdir -p dist && node_modules/.bin/webpack-dev-server --progress --colors --hot --inline'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the geonode-viewer package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     mkdir -p dist && node_modules/.bin/webpack-dev-server --progress --colors --hot --inline
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs geonode-viewer
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls geonode-viewer
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by bartvde** [comment]
Some of the dev commands are not compatible with Windows as a dev environment currently
